import type { UpdateEntry } from "./types";

export const UPDATE_ENTRIES: UpdateEntry[] = [
  {
    id: "structured-job-discovery",
    kind: "changelog",
    category: "discovery",
    date: "2026-08-31",
    href: "/opportunities",
    copy: {
      en: { title: "Structured job discovery", summary: "Added real job location, freshness, employment taxonomy, relevance search, saved jobs, comparison, persistent preferences, and explicit loading." },
      pt: { title: "Descoberta estruturada de vagas", summary: "Adicionamos localização real, atualidade, taxonomia de emprego, busca por relevância, vagas salvas, comparação, preferências persistentes e carregamento explícito." },
      es: { title: "Descubrimiento estructurado de vacantes", summary: "Añadimos ubicación real, actualidad, taxonomía laboral, búsqueda por relevancia, vacantes guardadas, comparación, preferencias persistentes y carga explícita." },
      it: { title: "Ricerca strutturata delle offerte", summary: "Abbiamo aggiunto località reale, attualità, tassonomia del lavoro, ricerca per rilevanza, offerte salvate, confronto, preferenze persistenti e caricamento esplicito." },
      fr: { title: "Découverte structurée des offres", summary: "Ajout de la localisation réelle, de la fraîcheur, d’une taxonomie de l’emploi, de la recherche par pertinence, des favoris, de la comparaison, des préférences persistantes et du chargement explicite." },
      de: { title: "Strukturierte Stellensuche", summary: "Neu sind tatsächlicher Arbeitsort, Aktualität, Job-Taxonomie, Relevanzsuche, gespeicherte Stellen, Vergleich, dauerhafte Einstellungen und bewusstes Nachladen." },
    },
  },
  {
    id: "public-sync-history-and-confidence",
    kind: "changelog",
    category: "trust",
    date: "2026-09-01",
    href: "/status",
    copy: {
      en: { title: "Public sync history and data confidence", summary: "Status now explains recent synchronization health, while each job identifies declared, inferred, and unavailable details." },
      pt: { title: "Histórico público e confiança dos dados", summary: "O status agora explica a saúde das sincronizações recentes, e cada vaga identifica detalhes declarados, inferidos e indisponíveis." },
      es: { title: "Historial público y confianza de los datos", summary: "El estado ahora explica la salud de las sincronizaciones recientes y cada vacante distingue datos declarados, inferidos y no disponibles." },
      it: { title: "Cronologia pubblica e affidabilità dei dati", summary: "Lo stato descrive ora la salute delle sincronizzazioni recenti e ogni offerta distingue dati dichiarati, dedotti e non disponibili." },
      fr: { title: "Historique public et fiabilité des données", summary: "L’état explique désormais la santé des synchronisations récentes et chaque offre distingue les données déclarées, déduites et indisponibles." },
      de: { title: "Öffentlicher Verlauf und Datenverlässlichkeit", summary: "Der Status erklärt jetzt die letzten Synchronisierungen; jede Stelle kennzeichnet angegebene, abgeleitete und nicht verfügbare Angaben." },
    },
  },
  {
    id: "release-2026-09",
    kind: "release",
    category: "trust",
    date: "2026-09-01",
    version: "2026.09",
    copy: {
      en: { title: "Structured discovery and public status", summary: "This release combines more reliable job discovery with transparent source synchronization and field-level confidence." },
      pt: { title: "Descoberta estruturada e status público", summary: "Esta versão combina descoberta de vagas mais confiável com sincronização transparente das fontes e confiança por campo." },
      es: { title: "Descubrimiento estructurado y estado público", summary: "Esta versión combina un descubrimiento más fiable con sincronización transparente de fuentes y confianza por campo." },
      it: { title: "Ricerca strutturata e stato pubblico", summary: "Questa versione unisce una ricerca più affidabile alla sincronizzazione trasparente delle fonti e all’affidabilità per campo." },
      fr: { title: "Découverte structurée et état public", summary: "Cette version associe une découverte plus fiable à une synchronisation transparente des sources et à la fiabilité par champ." },
      de: { title: "Strukturierte Suche und öffentlicher Status", summary: "Diese Version verbindet verlässlichere Stellensuche mit transparenter Quellensynchronisierung und Datenstatus pro Feld." },
    },
  },
  {
    id: "improve-source-coverage-and-confidence",
    kind: "roadmap",
    category: "data",
    lane: "now",
    copy: {
      en: { title: "Improve source coverage and field confidence", summary: "Add useful public communities and make structured fields more accurate without inventing missing facts." },
      pt: { title: "Melhorar cobertura e confiança dos campos", summary: "Adicionar comunidades públicas úteis e aumentar a precisão dos campos estruturados sem inventar dados ausentes." },
      es: { title: "Mejorar cobertura y confianza de los campos", summary: "Añadir comunidades públicas útiles y hacer más precisos los campos estructurados sin inventar datos ausentes." },
      it: { title: "Migliorare copertura e affidabilità dei campi", summary: "Aggiungere comunità pubbliche utili e rendere più precisi i campi strutturati senza inventare dati mancanti." },
      fr: { title: "Améliorer la couverture et la fiabilité des champs", summary: "Ajouter des communautés publiques utiles et rendre les champs structurés plus précis sans inventer les données absentes." },
      de: { title: "Quellenabdeckung und Feldverlässlichkeit verbessern", summary: "Nützliche öffentliche Communities ergänzen und strukturierte Felder präzisieren, ohne fehlende Angaben zu erfinden." },
    },
  },
  {
    id: "normalize-salary-and-expand-discovery",
    kind: "roadmap",
    category: "discovery",
    lane: "next",
    copy: {
      en: { title: "Normalize salary comparison and expand curated discovery", summary: "Make compensation easier to compare and broaden high-signal paths into the job collection." },
      pt: { title: "Normalizar salários e ampliar a descoberta curada", summary: "Facilitar a comparação de remuneração e ampliar caminhos de alta qualidade para encontrar vagas." },
      es: { title: "Normalizar salarios y ampliar el descubrimiento curado", summary: "Facilitar la comparación de remuneración y ampliar rutas de alta calidad para descubrir vacantes." },
      it: { title: "Normalizzare gli stipendi e ampliare la ricerca curata", summary: "Semplificare il confronto delle retribuzioni e ampliare i percorsi ad alta qualità verso le offerte." },
      fr: { title: "Normaliser les salaires et élargir la découverte éditorialisée", summary: "Faciliter la comparaison des rémunérations et élargir les parcours à forte valeur vers les offres." },
      de: { title: "Gehälter normalisieren und kuratierte Suche ausbauen", summary: "Vergütungen besser vergleichbar machen und hochwertige Wege in den Stellenbestand ausbauen." },
    },
  },
  {
    id: "local-applications-and-community-contributions",
    kind: "roadmap",
    category: "growth",
    lane: "later",
    copy: {
      en: { title: "Local application tracking and community contributions", summary: "Explore private, local application progress and a clear workflow for communities to maintain their presence." },
      pt: { title: "Acompanhamento local e contribuições das comunidades", summary: "Explorar o progresso privado e local de candidaturas e um fluxo claro para comunidades manterem sua presença." },
      es: { title: "Seguimiento local y contribuciones de comunidades", summary: "Explorar el progreso privado y local de candidaturas y un flujo claro para que las comunidades mantengan su presencia." },
      it: { title: "Monitoraggio locale e contributi delle comunità", summary: "Esplorare l’avanzamento privato e locale delle candidature e un flusso chiaro per la presenza delle comunità." },
      fr: { title: "Suivi local des candidatures et contributions des communautés", summary: "Explorer un suivi privé et local des candidatures ainsi qu’un processus clair permettant aux communautés de gérer leur présence." },
      de: { title: "Lokale Bewerbungsverfolgung und Community-Beiträge", summary: "Private lokale Bewerbungsfortschritte und einen klaren Pflegeprozess für Communities untersuchen." },
    },
  },
];
